version: "3"

volumes:
  keystore-postgres-data:
networks:
  keystore:

services:
  keystore:
    entrypoint: [ "sh", "-c", "/utils/wait_for_it.sh db:5432 && diesel migration run && ./target/debug/keystore server" ]
    build:
      context: .
      dockerfile: Dockerfile.local
    image: keystore
    environment:
      - DATABASE_URL=postgresql://keystore:keystore@db/keystore
      - STQ_PAYMENTS_DATABASE_URL=postgresql://keystore:keystore@db/keystore
      - RUST_LOG=keystore=debug
    ports:
      - "8000"
    networks:
      - keystore
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=keystore
      - POSTGRES_PASSWORD=keystore
      - POSTGRES_DB=keystore
    volumes:
      - keystore-postgres-data:/var/lib/postgresql/data
    networks:
      - keystore
