apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: payments-keystore
  labels:
    stack: payments
    app: keystore
spec:
  selector:
    matchLabels:
      app: keystore
      stack: payments
  replicas: 1
  template:
    metadata:
      name: payments-keystore
      labels:
        app: keystore
        stack: payments
    spec:
      imagePullSecrets:
      - name: stq
      containers:
      - name: keystore
        image: storiqateam/payments-keystore
        ports:
        - containerPort: 8000
        env:
        - name: RUN_MODE
          value: k8s
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: keystore=debug
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_URL
          value: postgresql://keystore:keystore@postgres/keystore
        volumeMounts:
        - name: conf
          mountPath: /app/config/
      volumes:
      - name: conf
        configMap:
          name: keystore
