[server]
host = "0.0.0.0"
port = 8000

[database]
url = "postgresql://keystore:keystore@localhost/keystore"
thread_pool_size = 4

[blockchain]
stq_contract_address = "ec827d2c2493ca90cc237f4f314979973f17f5a8"
stq_transfer_method_number = "a9059cbb"
stq_gas_limit = 100000
