[server]
host = "0.0.0.0"
port = 8000

[database]
url = "postgresql://keystore:keystore@localhost/keystore"
thread_pool_size = 4

[blockchain]
stq_contract_address = "1bf2092a42166b2ae19b7b23752e7d2dab5ba91a"
stq_transfer_method_number = "a9059cbb"
stq_gas_limit = 100000
ethereum_chain_id = 42
btc_network = "test"
