[server]
host = "0.0.0.0"
port = 8000

[database]
url = "postgresql://keystore:keystore@localhost/keystore"
thread_pool_size = 4

[blockchain]
stq_contract_address = "1bf2092a42166b2ae19b7b23752e7d2dab5ba91a"
stq_approve_method_number = "095ea7b3"
stq_transfer_from_method_number = "23b872dd"
stq_gas_limit = 60000
ethereum_chain_id = 42
btc_network = "test"
stq_controller_address = "630c70c639c7588eeb6c5a1ff2ec9a3af7cb5b34"
main_key = "9e41f07d31e44062c688c08aa99e57d8fda2cba546da31f6a075e1a252f48a93"
