openapi: 3.0.0
servers:
  - url: 'https://exchange.storiqa.com/v1'
  - url: 'http://exchange.storiqa.com/v1'
  - url: 'https://exchange.stq.cloud/v1'
  - url: 'http://exchange.stq.cloud/v1'
info:
  description: Api server for currency exchange.
  version: "1.0.2"
  title: Exchange
  contact:
    email: s.efremov@storiqa.com
tags:
  - name: exchange
    description: Get, sell, exchange.
paths:
  /exchange:
    post:
      summary: Exchange funds
      security: 
        - Bearer: []
      tags:
        - exchange
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/Internal'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeInput'
  /rate:
    post:
      summary: Reserves exchange rate for a period of time
      security: 
        - Bearer: []
      tags:
        - exchange
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateResponse'
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/Internal'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RateInput'
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            description: Error that comes with 404 status
            properties:
              code:
                type: string
                example: 404

              description:
                type: string
                example: Not found

    BadRequest:
      description: Most likely malformed json (this includes violating schema in terms of required fields, but not validations)
      content:
        application/json:
          schema:
            type: object
            description: Error that comes with 400 status
            properties:

              description:
                type: string
                example: Bad request
    UnprocessableEntity:
      description: Inputs were ok, but service was unable to process request. E.g. when we cannot exchange at the desired rate that we promised
      content:
        application/json:
          schema:
            type: object
            description: Error that comes with 422 status
            properties:

              description:
                type: string
                example: Unprocessable entity
    Unauthorized:
      description: Unauthorized to perform action
      content:
        application/json:
          schema:
            type: object
            description: Error that comes with 401 status
            properties:

              description:
                type: string
                example: Unauthorized
    Internal:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            description: Error that comes with 500 status
            properties:
              description:
                type: string
                example: Internal server error



  schemas:
    ExchangeResponse:
      type: object
      description: >
        Sell order.
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
        from:
          $ref: '#/components/schemas/Currency'
        to:
          $ref: '#/components/schemas/Currency'
        amount:
          $ref: '#/components/schemas/Value'
        actualRate:
          $ref: '#/components/schemas/Rate'
    RateResponse:
      type: object
      description: >
        Current exchange rate.
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
        from:
          $ref: '#/components/schemas/Currency'
        to:
          $ref: '#/components/schemas/Currency'
        amount:
          $ref: '#/components/schemas/Value'
        rate:
          $ref: '#/components/schemas/Rate'
        expiration:
          $ref: '#/components/schemas/TimeStamp'
        createdAt:
          $ref: '#/components/schemas/TimeStamp'
        updatedAt:
          $ref: '#/components/schemas/TimeStamp'
    Value:
      type: number
      description: Monetary value - either fiat or blockchain
      example: 185000000000000000000
    ExchangeInput:
      type: object
      required:
        - id
        - from
        - to
        - rate
        - actualAmount
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
        from:
          $ref: '#/components/schemas/Currency'
        to:
          $ref: '#/components/schemas/Currency'
        rate:
          $ref: '#/components/schemas/Rate'
        actualAmount:
          $ref: '#/components/schemas/Value'
    RateInput:
      type: object
      required:
        - id
        - from
        - to
        - amount
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
        from:
          $ref: '#/components/schemas/Currency'
        to:
          $ref: '#/components/schemas/Currency'
        amount:
          $ref: '#/components/schemas/Value'

    AccountAddress:
      type: string
      description: Either blockchain address or fiat account number (depending on currency)
      example: '0x89595fa59d69d696d9d96'
    Currency:
      type: string
      description: >-
        ISO 4217 alphabetic code for fiat currencies in CAPS
        [source](https://www.currency-iso.org/en/home/tables/table-a1.html). Or
        Coinmarketcap symbol in lower case [source](https://coinmarketcap.com/)
      example: eth
    Uuid:
      type: string
      description: Uuid v4
      example: '5188dde0-9dc3-461f-b272-dd3b1398c1dc'
    Rate:
      type: number
      description: exchange rate
      example: 0.0025
    TimeStamp:
      type: number
      description: unix timestamp
      example: 157239470
